# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'WeAr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
 

  target 'WeArTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WeAr-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeAr-tvOS

  target 'WeAr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
