# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeAr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeAr
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'WeArTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WeAr-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeAr-tvOS

  target 'WeAr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
